export const POSTGRES_READINESS_PROBE = Symbol('POSTGRES_READINESS_PROBE');
export const REDIS_READINESS_PROBE = Symbol('REDIS_READINESS_PROBE');
export const SERVER_CONFIG = Symbol('SERVER_CONFIG');
